# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always

    env_file: .env
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    networks:
      - app-network

  nodejs:
    build:
      args:
        - NODE_ENV=development
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DB_HOST=host.docker.internal
    ports:
      - "5000:5000"
    # volumes needed for dev only
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    depends_on: 
      - db

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  # node_modules volume needed for dev only
  node_modules: